### ISSUE TITLE
Cannot download object removal dataset

### ISSUE THREAD

**Issue by zoezhou1999** [Junggy/SCRREAM#1]
Hi authors
Thank you for the great work!
But I cannot download the object removal dataset. 
Could you please fix it?
Thank you!

**Comment by Junggy** [comment]
Hi! thanks for your interest on our dataset!

can you elaborate how you cannot download the removal dataset?

can you download the Indoor Reconstruction and SLAM dataset?
in that case, object reomval / scene editing data should be contained in each scene's subfolder with "_reduced"

Thanks!

**Comment by zoezhou1999** [comment]
Hi
Thank you for the reply!
It shows:
"
Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

"
I cannnot access the data even after 24 hours.

**Comment by Junggy** [comment]
Hmmm Interesting. as far as I know, issues like this can happen if file is too big and downloading took too much time.

I will try to upload with smaller zip files and update the link soon

thanks!

**Comment by Junggy** [comment]
I just updated the link. Try the new links and let me know whether it worked out.

Thanks!

**Comment by zoezhou1999** [comment]
Hi @Junggy 
Thank you very much! It works!
Great work!
